# Generated by Django 4.1.4 on 2022-12-15 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklistpolitext', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='add_data',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='ready_datatime',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='add_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 15, 13, 35, 27, 238721, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklist',
            name='ready_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Время готовности'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='operator',
            field=models.CharField(blank=True, choices=[('YURA', 'Юрий'), ('ZIYO', 'Зийо'), ('AZIZ', 'Азиз'), ('DIMA', 'Дмитрий'), ('ANDREY', 'Андрей'), ('OLEG', 'Олег')], max_length=255, verbose_name='Вывел'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='stage',
            field=models.CharField(choices=[('UNREADY', 'На машине'), ('READY', 'Готов')], default='На машине', max_length=255, verbose_name='Состояние'),
        ),
    ]
