# Generated by Django 4.1.4 on 2022-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklistpolitext', '0002_remove_tasklist_add_data_remove_tasklist_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='company_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Фирма'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='equipment',
            field=models.CharField(blank=True, choices=[('BLUE', 'Синяя'), ('GREEN', 'Зелёная'), ('AURORA', 'Аврора B0'), ('THERMAL', 'Термальная'), ('FIRST', 'Первая')], max_length=40, verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='file_name',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='plate_size',
            field=models.CharField(blank=True, max_length=40, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='qty',
            field=models.CharField(blank=True, max_length=40, verbose_name='Шт.'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='ready_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время готовности'),
        ),
    ]
